import type { OsId } from "./os-systems";

export type SoftwareCategory = "utility" | "pentest" | "gaming" | "creative";

export type CatalogApp = {
  id: string;
  name: string;
  blurb: string;
  category: SoftwareCategory;
  platforms: OsId[];
  url: string;
  github?: string;
  thumb: string;
  tags?: string[];
};

export const SOFTWARE_CATALOG: CatalogApp[] = [
  {
    id: "cpu-x",
    name: "CPU-X",
    blurb: "Free CPUID-style system info — CPU, motherboard, memory, and benchmarks.",
    category: "utility",
    platforms: ["linux", "win10", "win11"],
    url: "https://thetumultuousunicornofdarkness.github.io/CPU-X/",
    github: "https://github.com/TheTumultuousUnicornOfDarkness/CPU-X",
    thumb: "https://cdn.simpleicons.org/cplusplus/00599C",
    tags: ["cpuid", "hardware"],
  },
  {
    id: "libre-hardware-monitor",
    name: "LibreHardwareMonitor",
    blurb: "Open-source sensors for temps, fans, voltages, and clocks on Windows.",
    category: "utility",
    platforms: ["win10", "win11"],
    url: "https://github.com/LibreHardwareMonitor/LibreHardwareMonitor",
    github: "https://github.com/LibreHardwareMonitor/LibreHardwareMonitor",
    thumb: "https://cdn.simpleicons.org/windows/0078D4",
    tags: ["sensors", "temps"],
  },
  {
    id: "system-informer",
    name: "System Informer",
    blurb: "Modern Process Hacker fork — processes, handles, services, and more.",
    category: "utility",
    platforms: ["win10", "win11"],
    url: "https://systeminformer.sourceforge.io/",
    github: "https://github.com/winsiderss/systeminformer",
    thumb: "https://cdn.simpleicons.org/windows/00A4EF",
    tags: ["processes"],
  },
  {
    id: "powertoys",
    name: "PowerToys",
    blurb: "Microsoft’s open toolkit: FancyZones, Run, Color Picker, Awake, and more.",
    category: "utility",
    platforms: ["win10", "win11"],
    url: "https://learn.microsoft.com/windows/powertoys/",
    github: "https://github.com/microsoft/PowerToys",
    thumb: "https://cdn.simpleicons.org/microsoft/00A4EF",
    tags: ["productivity"],
  },
  {
    id: "7zip",
    name: "7-Zip",
    blurb: "High-compression archiver with solid FOSS roots. Everyday essential.",
    category: "utility",
    platforms: ["win10", "win11", "linux"],
    url: "https://www.7-zip.org/",
    thumb: "https://cdn.simpleicons.org/7zip/000000",
    tags: ["archives"],
  },
  {
    id: "notepadpp",
    name: "Notepad++",
    blurb: "Fast free source editor with plugins, macros, and multi-view.",
    category: "utility",
    platforms: ["win10", "win11"],
    url: "https://notepad-plus-plus.org/",
    github: "https://github.com/notepad-plus-plus/notepad-plus-plus",
    thumb: "https://cdn.simpleicons.org/notepadplusplus/90E59A",
  },
  {
    id: "btop",
    name: "btop",
    blurb: "Beautiful resource monitor for CPU, memory, disks, and network.",
    category: "utility",
    platforms: ["linux", "macos"],
    url: "https://github.com/aristocratos/btop",
    github: "https://github.com/aristocratos/btop",
    thumb: "https://cdn.simpleicons.org/linux/FCC624",
    tags: ["monitor"],
  },
  {
    id: "stats-mac",
    name: "Stats",
    blurb: "macOS menu-bar monitors for CPU, GPU, memory, network, and batteries.",
    category: "utility",
    platforms: ["macos"],
    url: "https://github.com/exelban/stats",
    github: "https://github.com/exelban/stats",
    thumb: "https://cdn.simpleicons.org/apple/000000",
  },
  {
    id: "rectangle",
    name: "Rectangle",
    blurb: "Snap windows on macOS with keyboard shortcuts — Spectacle successor.",
    category: "utility",
    platforms: ["macos"],
    url: "https://rectangleapp.com/",
    github: "https://github.com/rxhanson/Rectangle",
    thumb: "https://cdn.simpleicons.org/macos/000000",
  },
  {
    id: "keepassxc",
    name: "KeePassXC",
    blurb: "Offline password manager. Cross-platform, audited, no cloud required.",
    category: "utility",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://keepassxc.org/",
    github: "https://github.com/keepassxreboot/keepassxc",
    thumb: "https://cdn.simpleicons.org/keepassxc/1FA86C",
  },
  {
    id: "vlc",
    name: "VLC",
    blurb: "Plays almost anything. Free, no ads, available on every major platform.",
    category: "utility",
    platforms: ["win10", "win11", "macos", "linux", "android", "apple"],
    url: "https://www.videolan.org/vlc/",
    thumb: "https://cdn.simpleicons.org/vlcmediaplayer/FF8800",
  },
  {
    id: "handbrake",
    name: "HandBrake",
    blurb: "Open video transcoder with presets for devices and archival.",
    category: "utility",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://handbrake.fr/",
    github: "https://github.com/HandBrake/HandBrake",
    thumb: "https://cdn.simpleicons.org/handbrake/E6002A",
  },
  {
    id: "qbittorrent",
    name: "qBittorrent",
    blurb: "Clean BitTorrent client with search, RSS, and remote control.",
    category: "utility",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.qbittorrent.org/",
    github: "https://github.com/qbittorrent/qBittorrent",
    thumb: "https://cdn.simpleicons.org/qbittorrent/2F67D9",
  },
  {
    id: "utm",
    name: "UTM",
    blurb: "Virtual machines on Apple Silicon and Intel Macs — QEMU frontend.",
    category: "utility",
    platforms: ["macos", "apple"],
    url: "https://mac.getutm.app/",
    github: "https://github.com/utmapp/UTM",
    thumb: "https://cdn.simpleicons.org/qemu/FF6600",
  },
  {
    id: "termux",
    name: "Termux",
    blurb: "Full Linux environment on Android — packages, SSH, scripting.",
    category: "utility",
    platforms: ["android"],
    url: "https://termux.dev/",
    github: "https://github.com/termux/termux-app",
    thumb: "https://cdn.simpleicons.org/android/3DDC84",
    tags: ["terminal"],
  },
  {
    id: "fdroid",
    name: "F-Droid",
    blurb: "App store of free and open-source Android software only.",
    category: "utility",
    platforms: ["android"],
    url: "https://f-droid.org/",
    thumb: "https://cdn.simpleicons.org/fdroid/1976D2",
  },
  {
    id: "ish",
    name: "iSH",
    blurb: "Linux shell on iOS via usermode x86 emulation. Alpine packages.",
    category: "utility",
    platforms: ["apple"],
    url: "https://ish.app/",
    github: "https://github.com/ish-app/ish",
    thumb: "https://cdn.simpleicons.org/alpinelinux/0D597F",
  },
  {
    id: "a-shell",
    name: "a-Shell",
    blurb: "Local Unix terminal on iPhone/iPad with Python, Lua, and file access.",
    category: "utility",
    platforms: ["apple"],
    url: "https://holzschu.github.io/a-Shell_iOS/",
    github: "https://github.com/holzschu/a-shell",
    thumb: "https://cdn.simpleicons.org/apple/555555",
  },
  {
    id: "nmap",
    name: "Nmap",
    blurb: "Network mapper and port scanner — the recon classic.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://nmap.org/",
    thumb: "https://cdn.simpleicons.org/nmap/4682B4",
    tags: ["recon"],
  },
  {
    id: "wireshark",
    name: "Wireshark",
    blurb: "World-class packet capture and protocol analysis.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.wireshark.org/",
    github: "https://github.com/wireshark/wireshark",
    thumb: "https://cdn.simpleicons.org/wireshark/1679A7",
  },
  {
    id: "owasp-zap",
    name: "OWASP ZAP",
    blurb: "Free web app scanner and intercepting proxy (Burp alternative).",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.zaproxy.org/",
    github: "https://github.com/zaproxy/zaproxy",
    thumb: "https://cdn.simpleicons.org/owasp/000000",
  },
  {
    id: "metasploit",
    name: "Metasploit Framework",
    blurb: "Exploitation framework used worldwide for authorized testing.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.metasploit.com/",
    github: "https://github.com/rapid7/metasploit-framework",
    thumb: "https://cdn.simpleicons.org/kalilinux/557C94",
  },
  {
    id: "hashcat",
    name: "Hashcat",
    blurb: "GPU password recovery — advanced attacks and huge format support.",
    category: "pentest",
    platforms: ["win10", "win11", "linux"],
    url: "https://hashcat.net/hashcat/",
    github: "https://github.com/hashcat/hashcat",
    thumb: "https://cdn.simpleicons.org/gnubash/4EAA25",
  },
  {
    id: "john",
    name: "John the Ripper",
    blurb: "Fast multi-format password cracker (jumbo community builds).",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.openwall.com/john/",
    github: "https://github.com/openwall/john",
    thumb: "https://cdn.simpleicons.org/openbsd/F2CA30",
  },
  {
    id: "nuclei",
    name: "Nuclei",
    blurb: "Template-driven vulnerability scanner — fast and scriptable.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://docs.projectdiscovery.io/tools/nuclei/overview",
    github: "https://github.com/projectdiscovery/nuclei",
    thumb: "https://cdn.simpleicons.org/go/00ADD8",
  },
  {
    id: "sqlmap",
    name: "sqlmap",
    blurb: "Automatic SQL injection detection and exploitation tool.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://sqlmap.org/",
    github: "https://github.com/sqlmapproject/sqlmap",
    thumb: "https://cdn.simpleicons.org/python/3776AB",
  },
  {
    id: "ghidra",
    name: "Ghidra",
    blurb: "NSA’s free reverse-engineering suite — disassembler and decompiler.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://ghidra-sre.org/",
    thumb: "https://cdn.simpleicons.org/nsa/1B4F72",
  },
  {
    id: "impacket",
    name: "Impacket",
    blurb: "Python collection of network protocol classes — AD / Windows labs.",
    category: "pentest",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://github.com/fortra/impacket",
    github: "https://github.com/fortra/impacket",
    thumb: "https://cdn.simpleicons.org/python/FFD43B",
  },
  {
    id: "pcapdroid",
    name: "PCAPdroid",
    blurb: "No-root Android traffic capture and export to Wireshark.",
    category: "pentest",
    platforms: ["android"],
    url: "https://github.com/emanuele-f/PCAPdroid",
    github: "https://github.com/emanuele-f/PCAPdroid",
    thumb: "https://cdn.simpleicons.org/wireshark/1679A7",
  },
  {
    id: "netguard",
    name: "NetGuard",
    blurb: "No-root Android firewall — block apps from phone home.",
    category: "pentest",
    platforms: ["android"],
    url: "https://www.netguard.me/",
    github: "https://github.com/M66B/NetGuard",
    thumb: "https://cdn.simpleicons.org/android/3DDC84",
  },
  {
    id: "mobsf",
    name: "MobSF",
    blurb: "Mobile Security Framework — static & dynamic analysis for APK/IPA.",
    category: "pentest",
    platforms: ["linux", "macos", "win10", "win11"],
    url: "https://github.com/MobSF/Mobile-Security-Framework-MobSF",
    github: "https://github.com/MobSF/Mobile-Security-Framework-MobSF",
    thumb: "https://cdn.simpleicons.org/android/3DDC84",
  },
  {
    id: "godot",
    name: "Godot Engine",
    blurb: "Fully open-source game engine — 2D & 3D, lightweight, MIT license.",
    category: "gaming",
    platforms: ["win10", "win11", "macos", "linux", "android"],
    url: "https://godotengine.org/",
    github: "https://github.com/godotengine/godot",
    thumb: "https://cdn.simpleicons.org/godotengine/478CBF",
  },
  {
    id: "heroic",
    name: "Heroic Games Launcher",
    blurb: "Open launcher for Epic, GOG, and Amazon games on desktop.",
    category: "gaming",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://heroicgameslauncher.com/",
    github: "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher",
    thumb: "https://cdn.simpleicons.org/epicgames/FFFFFF",
  },
  {
    id: "lutris",
    name: "Lutris",
    blurb: "Linux gaming manager — Wine, Proton, emulators, and store clients.",
    category: "gaming",
    platforms: ["linux"],
    url: "https://lutris.net/",
    github: "https://github.com/lutris/lutris",
    thumb: "https://cdn.simpleicons.org/linux/FCC624",
  },
  {
    id: "bottles",
    name: "Bottles",
    blurb: "Run Windows software and games on Linux in isolated bottles.",
    category: "gaming",
    platforms: ["linux"],
    url: "https://usebottles.com/",
    github: "https://github.com/bottlesdevs/Bottles",
    thumb: "https://cdn.simpleicons.org/wine/B070D0",
  },
  {
    id: "retroarch",
    name: "RetroArch",
    blurb: "Frontend for libretro cores — decades of consoles in one app.",
    category: "gaming",
    platforms: ["win10", "win11", "macos", "linux", "android", "apple"],
    url: "https://www.retroarch.com/",
    thumb: "https://cdn.simpleicons.org/retroarch/000000",
  },
  {
    id: "dolphin",
    name: "Dolphin Emulator",
    blurb: "GameCube & Wii emulator — high compatibility, open source.",
    category: "gaming",
    platforms: ["win10", "win11", "macos", "linux", "android"],
    url: "https://dolphin-emu.org/",
    github: "https://github.com/dolphin-emu/dolphin",
    thumb: "https://cdn.simpleicons.org/nintendo/E60012",
  },
  {
    id: "ppsspp",
    name: "PPSSPP",
    blurb: "PSP emulator for PC, Android, and more — fast and polished.",
    category: "gaming",
    platforms: ["win10", "win11", "macos", "linux", "android"],
    url: "https://www.ppsspp.org/",
    github: "https://github.com/hrydgard/ppsspp",
    thumb: "https://cdn.simpleicons.org/sony/000000",
  },
  {
    id: "blender",
    name: "Blender",
    blurb: "3D creation suite — modeling, animation, VFX, and rendering.",
    category: "creative",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.blender.org/",
    github: "https://github.com/blender/blender",
    thumb: "https://cdn.simpleicons.org/blender/F5792A",
  },
  {
    id: "gimp",
    name: "GIMP",
    blurb: "GNU Image Manipulation Program — free Photoshop-class editor.",
    category: "creative",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.gimp.org/",
    thumb: "https://cdn.simpleicons.org/gimp/5C5543",
  },
  {
    id: "obs",
    name: "OBS Studio",
    blurb: "Stream and record with scenes, sources, and plugins.",
    category: "creative",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://obsproject.com/",
    github: "https://github.com/obsproject/obs-studio",
    thumb: "https://cdn.simpleicons.org/obsstudio/302E31",
  },
  {
    id: "kdenlive",
    name: "Kdenlive",
    blurb: "Non-linear video editor from KDE — timelines, effects, exports.",
    category: "creative",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://kdenlive.org/",
    github: "https://invent.kde.org/multimedia/kdenlive",
    thumb: "https://cdn.simpleicons.org/kdenlive/57B518",
  },
  {
    id: "audacity",
    name: "Audacity",
    blurb: "Audio recorder and editor — multi-track, effects, export.",
    category: "creative",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://www.audacityteam.org/",
    github: "https://github.com/audacity/audacity",
    thumb: "https://cdn.simpleicons.org/audacity/0000CC",
  },
  {
    id: "inkscape",
    name: "Inkscape",
    blurb: "Vector graphics editor — SVG-native, free alternative to Illustrator.",
    category: "creative",
    platforms: ["win10", "win11", "macos", "linux"],
    url: "https://inkscape.org/",
    thumb: "https://cdn.simpleicons.org/inkscape/000000",
  },
  {
    id: "newpipe",
    name: "NewPipe",
    blurb: "Lightweight YouTube client for Android — no Google account needed.",
    category: "utility",
    platforms: ["android"],
    url: "https://newpipe.net/",
    github: "https://github.com/TeamNewPipe/NewPipe",
    thumb: "https://cdn.simpleicons.org/youtube/FF0000",
  },
  {
    id: "organic-maps",
    name: "Organic Maps",
    blurb: "Offline maps from OpenStreetMap — privacy-friendly navigation.",
    category: "utility",
    platforms: ["android", "apple"],
    url: "https://organicmaps.app/",
    github: "https://github.com/organicmaps/organicmaps",
    thumb: "https://cdn.simpleicons.org/openstreetmap/7EBC6F",
  },
  {
    id: "signal",
    name: "Signal",
    blurb: "Encrypted messaging — open protocol, free clients everywhere.",
    category: "utility",
    platforms: ["win10", "win11", "macos", "linux", "android", "apple"],
    url: "https://signal.org/",
    github: "https://github.com/signalapp/Signal-Android",
    thumb: "https://cdn.simpleicons.org/signal/3A76F0",
  },
  {
    id: "iina",
    name: "IINA",
    blurb: "Modern open-source media player built for macOS.",
    category: "utility",
    platforms: ["macos"],
    url: "https://iina.io/",
    github: "https://github.com/iina/iina",
    thumb: "https://cdn.simpleicons.org/apple/000000",
  },
  {
    id: "sharex",
    name: "ShareX",
    blurb: "Screenshots, GIFs, OCR, upload workflows — Windows powerhouse.",
    category: "utility",
    platforms: ["win10", "win11"],
    url: "https://getsharex.com/",
    github: "https://github.com/ShareX/ShareX",
    thumb: "https://cdn.simpleicons.org/sharex/2885F2",
  },
];

export const CATEGORY_LABEL: Record<SoftwareCategory, string> = {
  utility: "Utility",
  pentest: "Pentest / Security",
  gaming: "Gaming",
  creative: "Creative",
};

export function appsForOs(os: OsId, category?: SoftwareCategory | "all"): CatalogApp[] {
  return SOFTWARE_CATALOG.filter((app) => {
    if (!app.platforms.includes(os)) return false;
    if (category && category !== "all" && app.category !== category) return false;
    return true;
  });
}
