/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApparelIndexRouteImport } from './routes/apparel/index'
import { Route as ApparelIdRouteImport } from './routes/apparel/$id'
import { Route as ComputasIndexRouteImport } from './routes/computas/index'
import { Route as ComputasNewsRouteImport } from './routes/computas/news'
import { Route as ComputasPolicyRouteImport } from './routes/computas/policy'
import { Route as ComputasShopRouteRouteImport } from './routes/computas/shop/route'
import { Route as SoftwareIndexRouteImport } from './routes/software/index'
import { Route as SoftwareOverlayRouteImport } from './routes/software/overlay'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffApplyRouteImport } from './routes/staff/apply'
import { Route as StaffApproveRouteImport } from './routes/staff/approve'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffOverlayRouteImport } from './routes/staff/overlay'
import { Route as StaffPrintablesRouteImport } from './routes/staff/printables'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ComputasShopIndexRouteImport } from './routes/computas/shop/index'
import { Route as ComputasShopIdRouteImport } from './routes/computas/shop/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelIndexRoute = ApparelIndexRouteImport.update({
  id: '/apparel/',
  path: '/apparel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelIdRoute = ApparelIdRouteImport.update({
  id: '/apparel/$id',
  path: '/apparel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputasIndexRoute = ComputasIndexRouteImport.update({
  id: '/computas/',
  path: '/computas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputasNewsRoute = ComputasNewsRouteImport.update({
  id: '/computas/news',
  path: '/computas/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputasPolicyRoute = ComputasPolicyRouteImport.update({
  id: '/computas/policy',
  path: '/computas/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputasShopRouteRoute = ComputasShopRouteRouteImport.update({
  id: '/computas/shop',
  path: '/computas/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIndexRoute = SoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareOverlayRoute = SoftwareOverlayRouteImport.update({
  id: '/software/overlay',
  path: '/software/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffApplyRoute = StaffApplyRouteImport.update({
  id: '/staff/apply',
  path: '/staff/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffApproveRoute = StaffApproveRouteImport.update({
  id: '/staff/approve',
  path: '/staff/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOverlayRoute = StaffOverlayRouteImport.update({
  id: '/staff/overlay',
  path: '/staff/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPrintablesRoute = StaffPrintablesRouteImport.update({
  id: '/staff/printables',
  path: '/staff/printables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputasShopIndexRoute = ComputasShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComputasShopRouteRoute,
} as any)
const ComputasShopIdRoute = ComputasShopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComputasShopRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/computas/shop': typeof ComputasShopRouteRouteWithChildren
  '/apparel/$id': typeof ApparelIdRoute
  '/computas/news': typeof ComputasNewsRoute
  '/computas/policy': typeof ComputasPolicyRoute
  '/software/overlay': typeof SoftwareOverlayRoute
  '/staff/apply': typeof StaffApplyRoute
  '/staff/approve': typeof StaffApproveRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/overlay': typeof StaffOverlayRoute
  '/staff/printables': typeof StaffPrintablesRoute
  '/apparel/': typeof ApparelIndexRoute
  '/computas/': typeof ComputasIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/computas/shop/$id': typeof ComputasShopIdRoute
  '/computas/shop/': typeof ComputasShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/apparel/$id': typeof ApparelIdRoute
  '/computas/news': typeof ComputasNewsRoute
  '/computas/policy': typeof ComputasPolicyRoute
  '/software/overlay': typeof SoftwareOverlayRoute
  '/staff/apply': typeof StaffApplyRoute
  '/staff/approve': typeof StaffApproveRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/overlay': typeof StaffOverlayRoute
  '/staff/printables': typeof StaffPrintablesRoute
  '/apparel': typeof ApparelIndexRoute
  '/computas': typeof ComputasIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/computas/shop/$id': typeof ComputasShopIdRoute
  '/computas/shop': typeof ComputasShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/computas/shop': typeof ComputasShopRouteRouteWithChildren
  '/apparel/$id': typeof ApparelIdRoute
  '/computas/news': typeof ComputasNewsRoute
  '/computas/policy': typeof ComputasPolicyRoute
  '/software/overlay': typeof SoftwareOverlayRoute
  '/staff/apply': typeof StaffApplyRoute
  '/staff/approve': typeof StaffApproveRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/overlay': typeof StaffOverlayRoute
  '/staff/printables': typeof StaffPrintablesRoute
  '/apparel/': typeof ApparelIndexRoute
  '/computas/': typeof ComputasIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/computas/shop/$id': typeof ComputasShopIdRoute
  '/computas/shop/': typeof ComputasShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/login'
    | '/computas/shop'
    | '/apparel/$id'
    | '/computas/news'
    | '/computas/policy'
    | '/software/overlay'
    | '/staff/apply'
    | '/staff/approve'
    | '/staff/login'
    | '/staff/overlay'
    | '/staff/printables'
    | '/apparel/'
    | '/computas/'
    | '/software/'
    | '/staff/'
    | '/api/auth/$'
    | '/computas/shop/$id'
    | '/computas/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/login'
    | '/apparel/$id'
    | '/computas/news'
    | '/computas/policy'
    | '/software/overlay'
    | '/staff/apply'
    | '/staff/approve'
    | '/staff/login'
    | '/staff/overlay'
    | '/staff/printables'
    | '/apparel'
    | '/computas'
    | '/software'
    | '/staff'
    | '/api/auth/$'
    | '/computas/shop/$id'
    | '/computas/shop'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/login'
    | '/computas/shop'
    | '/apparel/$id'
    | '/computas/news'
    | '/computas/policy'
    | '/software/overlay'
    | '/staff/apply'
    | '/staff/approve'
    | '/staff/login'
    | '/staff/overlay'
    | '/staff/printables'
    | '/apparel/'
    | '/computas/'
    | '/software/'
    | '/staff/'
    | '/api/auth/$'
    | '/computas/shop/$id'
    | '/computas/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  ComputasShopRouteRoute: typeof ComputasShopRouteRouteWithChildren
  ApparelIdRoute: typeof ApparelIdRoute
  ComputasNewsRoute: typeof ComputasNewsRoute
  ComputasPolicyRoute: typeof ComputasPolicyRoute
  SoftwareOverlayRoute: typeof SoftwareOverlayRoute
  StaffApplyRoute: typeof StaffApplyRoute
  StaffApproveRoute: typeof StaffApproveRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffOverlayRoute: typeof StaffOverlayRoute
  StaffPrintablesRoute: typeof StaffPrintablesRoute
  ApparelIndexRoute: typeof ApparelIndexRoute
  ComputasIndexRoute: typeof ComputasIndexRoute
  SoftwareIndexRoute: typeof SoftwareIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel/': {
      id: '/apparel/'
      path: '/apparel'
      fullPath: '/apparel/'
      preLoaderRoute: typeof ApparelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel/$id': {
      id: '/apparel/$id'
      path: '/apparel/$id'
      fullPath: '/apparel/$id'
      preLoaderRoute: typeof ApparelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computas/': {
      id: '/computas/'
      path: '/computas'
      fullPath: '/computas/'
      preLoaderRoute: typeof ComputasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computas/news': {
      id: '/computas/news'
      path: '/computas/news'
      fullPath: '/computas/news'
      preLoaderRoute: typeof ComputasNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computas/policy': {
      id: '/computas/policy'
      path: '/computas/policy'
      fullPath: '/computas/policy'
      preLoaderRoute: typeof ComputasPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computas/shop': {
      id: '/computas/shop'
      path: '/computas/shop'
      fullPath: '/computas/shop'
      preLoaderRoute: typeof ComputasShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/': {
      id: '/software/'
      path: '/software'
      fullPath: '/software/'
      preLoaderRoute: typeof SoftwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/overlay': {
      id: '/software/overlay'
      path: '/software/overlay'
      fullPath: '/software/overlay'
      preLoaderRoute: typeof SoftwareOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/apply': {
      id: '/staff/apply'
      path: '/staff/apply'
      fullPath: '/staff/apply'
      preLoaderRoute: typeof StaffApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/approve': {
      id: '/staff/approve'
      path: '/staff/approve'
      fullPath: '/staff/approve'
      preLoaderRoute: typeof StaffApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/overlay': {
      id: '/staff/overlay'
      path: '/staff/overlay'
      fullPath: '/staff/overlay'
      preLoaderRoute: typeof StaffOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/printables': {
      id: '/staff/printables'
      path: '/staff/printables'
      fullPath: '/staff/printables'
      preLoaderRoute: typeof StaffPrintablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computas/shop/': {
      id: '/computas/shop/'
      path: '/'
      fullPath: '/computas/shop/'
      preLoaderRoute: typeof ComputasShopIndexRouteImport
      parentRoute: typeof ComputasShopRouteRoute
    }
    '/computas/shop/$id': {
      id: '/computas/shop/$id'
      path: '/$id'
      fullPath: '/computas/shop/$id'
      preLoaderRoute: typeof ComputasShopIdRouteImport
      parentRoute: typeof ComputasShopRouteRoute
    }
  }
}

interface ComputasShopRouteRouteChildren {
  ComputasShopIdRoute: typeof ComputasShopIdRoute
  ComputasShopIndexRoute: typeof ComputasShopIndexRoute
}

const ComputasShopRouteRouteChildren: ComputasShopRouteRouteChildren = {
  ComputasShopIdRoute: ComputasShopIdRoute,
  ComputasShopIndexRoute: ComputasShopIndexRoute,
}

const ComputasShopRouteRouteWithChildren =
  ComputasShopRouteRoute._addFileChildren(ComputasShopRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  ComputasShopRouteRoute: ComputasShopRouteRouteWithChildren,
  ApparelIdRoute: ApparelIdRoute,
  ComputasNewsRoute: ComputasNewsRoute,
  ComputasPolicyRoute: ComputasPolicyRoute,
  SoftwareOverlayRoute: SoftwareOverlayRoute,
  StaffApplyRoute: StaffApplyRoute,
  StaffApproveRoute: StaffApproveRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffOverlayRoute: StaffOverlayRoute,
  StaffPrintablesRoute: StaffPrintablesRoute,
  ApparelIndexRoute: ApparelIndexRoute,
  ComputasIndexRoute: ComputasIndexRoute,
  SoftwareIndexRoute: SoftwareIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
